php:
  build: ./php
  ports:
    - "80:80"
    - "443:443"
  volumes:
    - .:/var/www/html
  links:
    - db
db:
  image: mysql:5.7
  volumes:
    - /var/lib/mysql
  environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=teste
